services:
  - type: web
    name: freshrss-batman
    env: docker
    plan: free
    region: frankfurt # Or your preferred region
    envVars:
      - key: FRESHRSS_INSTALL
        value: '--db-type postgres --db-host aws-1-eu-north-1.pooler.supabase.com --db-user postgres.qzztnegumuramsdcapni --db-password [YOUR-PASSWORD] --db-base postgres --db-port 6543 --db-prefix freshrss_ --default-user admin --api-enabled --auth-type form'
      - key: DATABASE_TYPE
        value: postgres
      - key: DATABASE_HOST
        value: aws-1-eu-north-1.pooler.supabase.com
      - key: DATABASE_PORT
        value: "6543"
      - key: DATABASE_USER
        value: postgres.qzztnegumuramsdcapni
      - key: DATABASE_PASSWORD
        value: SupabaseRss_2020